### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BlueVolt1** [SirLpc/GenerateObfuscarConfigForUnity#1]
Hi SirLpc,
I would like to ask you questions for this script.
It would be really helpful if you could add me on Discord BlueVolt#0687
Thank you

**Comment by myNameispiaofei** [comment]
可以有完整的demo么

**Comment by SirLpc** [comment]
> 可以有完整的demo么

Thanks for your interesting, a sample project has been made: 
https://github.com/SirLpc/GenerateObfuscarConfigForUnity_sample
